image: marcopeg/gitpod-workspace-postgres:2.5.0

tasks:
  - name: Unit Tests
    init: sleep 30
    command: yarn tdd:unit
    openIn: right
    openMode: tab-after
  - name: E2E Tests
    init: sleep 30
    command: yarn tdd:e2e
    openIn: right
    openMode: tab-after
  - name: Api
    init: yarn install
    command: yarn start:gitpod:api
    openIn: bottom
    openMode: tab-after
  - name: Styleguide
    init: sleep 30
    command: yarn start:styleguide
    openIn: bottom
    openMode: split-right
  - name: App
    init: sleep 30
    command: yarn start:gitpod:app
    openIn: bottom
    openMode: tab-after

ports:
  - port: 5432
    onOpen: ignore
  - port: 8008
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 3000
    onOpen: ignore
  - port: 6060
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
