export const f1 = {
  success: true,
  data: {
    logs: [
      {
        group_name: 'foo',
        task_name: 'a001',
        created_at: '2020-03-30T11:44:32.402Z',
        cursor: 94160054918,
        message: '200 OK',
        ref_id: 'null',
        log_id: 6587,
        type: 'response',
        data: {
          config: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            body: {},
            type: 'rest',
            rules: [{ match: ['all'] }],
            method: 'GET',
            headers: [],
          },
          result: { emotion: '💩', message: '+ok', success: true },
          request: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            method: 'GET',
            headers: [],
          },
          response: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            size: 0,
            status: 200,
            headers: {
              _headers: {
                via: ['1.1 vegur'],
                date: ['Mon, 30 Mar 2020 11:44:32 GMT'],
                server: ['Cowboy'],
                connection: ['close'],
                'content-type': ['application/json; charset=utf-8'],
                'content-length': ['49'],
              },
            },
            statusText: 'OK',
          },
          variables: {
            payload: {},
            attempts: 1,
            schedule: { value: '1s', method: 'delay' },
            created_at: '2020-03-30T11:44:23.620Z',
            iterations: 5,
            next_iteration: '2020-03-30T11:49:32.301Z',
          },
        },
      },
      {
        group_name: 'foo',
        task_name: 'a001',
        created_at: '2020-03-30T11:44:30.894Z',
        cursor: 94158547936,
        message: '200 OK',
        ref_id: 'null',
        log_id: 6586,
        type: 'response',
        data: {
          config: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            body: {},
            type: 'rest',
            rules: [{ match: ['all'] }],
            method: 'GET',
            headers: [],
          },
          result: { emotion: '💩', message: '+ok', success: true },
          request: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            method: 'GET',
            headers: [],
          },
          response: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            size: 0,
            status: 200,
            headers: {
              _headers: {
                via: ['1.1 vegur'],
                date: ['Mon, 30 Mar 2020 11:44:30 GMT'],
                server: ['Cowboy'],
                connection: ['close'],
                'content-type': ['application/json; charset=utf-8'],
                'content-length': ['49'],
              },
            },
            statusText: 'OK',
          },
          variables: {
            payload: {},
            attempts: 1,
            schedule: { value: '1s', method: 'delay' },
            created_at: '2020-03-30T11:44:23.620Z',
            iterations: 4,
            next_iteration: '2020-03-30T11:49:30.795Z',
          },
        },
      },
      {
        group_name: 'foo',
        task_name: 'a001',
        created_at: '2020-03-30T11:44:29.557Z',
        cursor: 94157211126,
        message: '200 OK',
        ref_id: 'null',
        log_id: 6585,
        type: 'response',
        data: {
          config: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            body: {},
            type: 'rest',
            rules: [{ match: ['all'] }],
            method: 'GET',
            headers: [],
          },
          result: { emotion: '💩', message: '+ok', success: true },
          request: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            method: 'GET',
            headers: [],
          },
          response: {
            url: 'https://fetchq-cron.herokuapp.com/ping',
            size: 0,
            status: 200,
            headers: {
              _headers: {
                via: ['1.1 vegur'],
                date: ['Mon, 30 Mar 2020 11:44:29 GMT'],
                server: ['Cowboy'],
                connection: ['close'],
                'content-type': ['application/json; charset=utf-8'],
                'content-length': ['49'],
              },
            },
            statusText: 'OK',
          },
          variables: {
            payload: {},
            attempts: 1,
            schedule: { value: '1s', method: 'delay' },
            created_at: '2020-03-30T11:44:23.620Z',
            iterations: 3,
            next_iteration: '2020-03-30T11:49:29.348Z',
          },
        },
      },
    ],
  },
};
