export const f1 = {
  success: true,
  data: {
    logs: [
      {
        group: 'foo',
        task: 'a001',
        created_at: '2020-03-29T12:16:06.336Z',
        cursor: 7582695696,
        message: '200 OK',
        details: {
          data: {
            config: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              body: {},
              type: 'rest',
              rules: [{ match: ['all'] }],
              method: 'GET',
              headers: [],
            },
            result: { emotion: '💩', message: '+ok', success: true },
            request: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              method: 'GET',
              headers: [],
            },
            response: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              size: 0,
              status: 200,
              headers: {
                _headers: {
                  via: ['1.1 vegur'],
                  date: ['Sun, 29 Mar 2020 12:16:06 GMT'],
                  server: ['Cowboy'],
                  connection: ['close'],
                  'content-type': ['application/json; charset=utf-8'],
                  'content-length': ['49'],
                },
              },
              statusText: 'OK',
            },
            variables: {
              payload: {},
              attempts: 1,
              schedule: { value: '1s', method: 'delay' },
              created_at: '2020-03-29T12:14:50.840Z',
              iterations: 27,
              next_iteration: '2020-03-29T12:21:06.255Z',
            },
          },
          type: 'response',
          cursor: 7582695696,
          task_name: 'a001',
          group_name: 'foo',
        },
        ref_id: 'null',
      },
      {
        group: 'foo',
        task: 'a001',
        created_at: '2020-03-29T12:16:04.859Z',
        cursor: 7581219455,
        message: '200 OK',
        details: {
          data: {
            config: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              body: {},
              type: 'rest',
              rules: [{ match: ['all'] }],
              method: 'GET',
              headers: [],
            },
            result: { emotion: '💩', message: '+ok', success: true },
            request: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              method: 'GET',
              headers: [],
            },
            response: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              size: 0,
              status: 200,
              headers: {
                _headers: {
                  via: ['1.1 vegur'],
                  date: ['Sun, 29 Mar 2020 12:16:04 GMT'],
                  server: ['Cowboy'],
                  connection: ['close'],
                  'content-type': ['application/json; charset=utf-8'],
                  'content-length': ['49'],
                },
              },
              statusText: 'OK',
            },
            variables: {
              payload: {},
              attempts: 1,
              schedule: { value: '1s', method: 'delay' },
              created_at: '2020-03-29T12:14:50.840Z',
              iterations: 26,
              next_iteration: '2020-03-29T12:21:04.751Z',
            },
          },
          type: 'response',
          cursor: 7581219455,
          task_name: 'a001',
          group_name: 'foo',
        },
        ref_id: 'null',
      },
      {
        group: 'foo',
        task: 'a001',
        created_at: '2020-03-29T12:16:03.355Z',
        cursor: 7579714780,
        message: '200 OK',
        details: {
          data: {
            config: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              body: {},
              type: 'rest',
              rules: [{ match: ['all'] }],
              method: 'GET',
              headers: [],
            },
            result: { emotion: '💩', message: '+ok', success: true },
            request: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              method: 'GET',
              headers: [],
            },
            response: {
              url: 'https://fetchq-cron.herokuapp.com/ping',
              size: 0,
              status: 200,
              headers: {
                _headers: {
                  via: ['1.1 vegur'],
                  date: ['Sun, 29 Mar 2020 12:16:03 GMT'],
                  server: ['Cowboy'],
                  connection: ['close'],
                  'content-type': ['application/json; charset=utf-8'],
                  'content-length': ['49'],
                },
              },
              statusText: 'OK',
            },
            variables: {
              payload: {},
              attempts: 1,
              schedule: { value: '1s', method: 'delay' },
              created_at: '2020-03-29T12:14:50.840Z',
              iterations: 25,
              next_iteration: '2020-03-29T12:21:03.247Z',
            },
          },
          type: 'response',
          cursor: 7579714780,
          task_name: 'a001',
          group_name: 'foo',
        },
        ref_id: 'null',
      },
    ],
  },
};
